# problems/maze/config.py
"""Maze problem configuration."""

from typing import Optional

from agent_genesis import PhaseConfig


class MazeConfig(PhaseConfig):
    """Maze-specific problem configuration."""

    # =========== Maze-specific parameters ===========
    seed: Optional[int] = None  # None = random seed (anti-cheat)
    maze_width: int = 5
    maze_height: int = 5
    wall_density: float = 0.15
    max_moves: int = 200

    # =========== Evaluation parameters ===========
    num_cases: int = 3
    min_passed_cases: Optional[int] = None  # None = all must pass (PhaseConfig default)
    parallel_cases: int = 5
    time_limit: float = 650.0
    # Keep overall sandbox timeout above case time_limit to avoid premature worker fallback.
    sandbox_timeout: int = 750
    case_idle_timeout: int = 60  # per-step idle timeout (seconds)

    # =========== Judge script dependencies (installed at runtime) ===========
    pip_dependencies: list[str] = [
        "openai",     # LLM API calls
        "pydantic",   # data validation
    ]

    # =========== User bridge (auto-generated by evaluator from config) ===========
    solve_attr_name: str = "solve"
    adapter_preset: str = "maze"

    # =========== Private files (specified by problem author) ===========
    # Only listed files are private; unlisted files default to public.
    # [] = all public, None = no manifest injection (contributors cannot modify artifacts)
    private_files: Optional[list[str]] = []

    # =========== Evaluator metadata ===========
    evaluator_module: str = "agent_genesis.dual_sandbox_evaluator"
    evaluator_class: str = "DualSandboxEvaluator"


# =========== Localized problem content ===========
MAZE_OVERVIEW_EN = "Use an LLM Agent to navigate through random mazes and find the exit."
MAZE_OVERVIEW_ZH = "让一个 LLM 智能体通过工具调用在随机迷宫中探索并找到出口。"

# =========== Phase description and starter code (English) ===========
MAZE_BACKGROUND = """
# Maze Agent Background Knowledge

This problem trains an LLM-driven agent to solve an **unknown maze** through interactive feedback.

## Why this is challenging

- The full map is hidden; the agent only gets textual feedback from each move.
- Feedback wording is semantically randomized, so brittle keyword matching is unreliable.
- The policy must combine exploration, memory, and stop conditions under move/time constraints.

## Core strategy ideas

- Keep an internal state (visited paths, blocked directions, current hypothesis of layout).
- Use tool-calling interaction as the main control loop: observe -> decide -> call `move` -> update context.
- Detect success robustly from semantic meaning, then terminate immediately to avoid penalties.

## Engineering hints

- Treat `move(direction)` as the only environment API and design around delayed feedback.
- Add safeguards for loops and repeated dead-end traversals.
- Make the logic resilient to paraphrased success/failure messages.
""".strip()

MAZE_BACKGROUND_ZH = """
# 迷宫智能体背景知识

本题训练一个由 LLM 驱动的智能体，在**未知迷宫**中通过交互反馈完成寻路。

## 为什么这题有挑战

- 完整地图不可见，智能体每一步只能拿到环境返回的文本反馈。
- 反馈描述有语义随机化，依赖固定关键词的脆弱规则不可靠。
- 你需要在步数与时间约束下，同时处理探索、记忆和终止判断。

## 核心思路

- 维护内部状态（已访问路径、受阻方向、当前布局假设）。
- 以工具调用为主循环：观察 -> 决策 -> 调用 `move` -> 更新上下文。
- 基于语义稳健识别“到达终点”，并在成功后立刻结束以避免额外罚分。

## 工程建议

- 将 `move(direction)` 视为唯一环境 API，并围绕其阻塞式反馈来设计策略。
- 为死循环和重复撞墙路径增加保护机制。
- 对成功/失败反馈的多种表达保持鲁棒，不依赖单一措辞。
""".strip()

PHASE1_DESCRIPTION = """
# Phase 1: Basic Maze (Interactive Agent)

Implement an Agent that navigates from a start point to an end point in a random maze.

Each test case generates a different maze; you cannot read the full map, only interact via `move`.

## 1. Interface

```python
def solve(move):
    result = move("right")  # execute one step, returns environment text feedback
    ...                     # must return immediately upon reaching the goal
```

- `move(direction)`
  - Effect: execute one move, **blocking** until the environment returns feedback
  - Parameter: `"up"` / `"down"` / `"left"` / `"right"`
  - Returns: environment text feedback (`str`)
- `solve(move)`
  - Call `move(...)` in a loop to explore the maze
  - When you semantically confirm reaching the goal, you must `return` immediately

## 2. Maze constraints

- The outermost ring is always walls; the interior contains paths and walls
- You cannot read coordinates, grids, or the full map
- You can only judge the state from `move` text feedback:
  - Whether the move succeeded
  - Whether you hit a wall
  - Whether you reached the goal
- Feedback text is **semantically randomized**; do not hard-code pattern matching

## 3. Scoring

- Reaching the goal = pass
- Fewer moves = higher score
- Constraints:
  - Max `200` moves per case
  - Total time limit `500` seconds
  - Per-step idle timeout `60` seconds

## 4. Termination (important)

- When `move()` returns text clearly indicating "goal reached", you must `return` immediately
- After reaching the goal or hitting the move limit, the case ends (no more actions requested)
- The following count as failure:
  - Timeout
  - Runtime error
  - Exceeding move limit
  - Not reaching the goal
""".strip()

PHASE1_DESCRIPTION_ZH = """
# 第一阶段：基础迷宫（交互式智能体）

实现一个智能体，从随机迷宫的起点导航到终点。

每个测试用例都会生成不同迷宫；你无法读取完整地图，只能通过 `move` 交互。

## 1. 接口

```python
def solve(move):
    result = move("right")  # 执行一步，返回环境文本反馈
    ...                     # 识别到到达终点后必须立刻 return
```

- `move(direction)`
  - 作用：执行一次移动，**阻塞**直到环境返回反馈
  - 参数：`"up"` / `"down"` / `"left"` / `"right"`
  - 返回：环境文本反馈（`str`）
- `solve(move)`
  - 在循环中持续调用 `move(...)` 完成探索
  - 当你从语义上确认到达终点时，必须立刻 `return`

## 2. 迷宫约束

- 迷宫最外圈恒为墙，内部包含通路和障碍
- 不提供坐标、网格或完整地图
- 你只能从 `move` 的文本反馈判断：
  - 这一步是否成功
  - 是否撞墙
  - 是否到达终点
- 反馈文本会**语义随机化**，不要写死关键词匹配

## 3. 评分

- 到达终点即通过
- 用步数越少，得分越高
- 约束：
  - 每个用例最多 `200` 步
  - 总时限 `500` 秒
  - 单步空闲超时 `60` 秒

## 4. 终止规则（重要）

- 当 `move()` 返回文本明确表示“已到达终点”时，必须立即 `return`
- 到达终点或超过步数上限后，用例结束（不会再请求动作）
- 以下情况判失败：
  - 超时
  - 运行时错误
  - 超过步数限制
  - 未到达终点
""".strip()

PHASE1_STARTER_CODE = r'''
def solve(move):
    """
    Interactive maze Agent

    Args:
        move: movement function, move(direction) -> str
              direction: "up" | "down" | "left" | "right"
              Returns environment text feedback (semantically randomized)

    Call move(direction) in a loop to explore the maze.
    When feedback indicates the goal is reached, return immediately.
    """
    # TODO: implement your maze exploration strategy
    pass
'''.strip()

PHASE1_STARTER_CODE_ZH = r'''
def solve(move):
    """
    交互式迷宫智能体

    Args:
        move: 移动函数，move(direction) -> str
              direction: "up" | "down" | "left" | "right"
              返回环境文本反馈（语义随机化）

    你需要在循环中调用 move(direction) 进行探索。
    当反馈表明已到达终点时，必须立即 return。
    """
    # TODO: 在这里实现你的迷宫探索策略
    pass
'''.strip()
