# problems/log_hunter/sandbox/generator.py
"""
Log Hunter - Semantic Quagmire v10
5M tokens of log data. Find 3 hacker IPs through semantic understanding.
- ALL reasons generated by LLM dynamically
- Usernames from SHARED POOL (both hacker and normal use same pool, randomly assigned)
- Cannot distinguish hacker/normal by username - must use semantic analysis of reasons
- Regex cannot match, must use LLM semantic understanding
- Requires MapReduce architecture to process 5M tokens
"""

import random
import os
import asyncio

# LLM client setup
try:
    from openai import AsyncOpenAI
    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False


def get_llm_client():
    """Get LLM client from environment"""
    if not HAS_OPENAI:
        return None
    api_key = os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY")
    base_url = os.getenv("LLM_BASE_URL", "https://api.deepseek.com")
    if not api_key:
        return None
    return AsyncOpenAI(api_key=api_key, base_url=base_url)


def generate_random_ip() -> str:
    """Generate random IP"""
    return f"{random.randint(1,255)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"


# Shared username pool - both hacker and normal users draw from this
# Mix of normal employee names and system-style names to prevent pattern matching
SHARED_USER_POOL = [
    # Normal employee names
    "john_smith", "alice_wong", "bob_chen", "carol_davis", "david_kim",
    "emma_lee", "frank_liu", "grace_brown", "henry_wang", "iris_zhao",
    "jack_taylor", "kate_miller", "leo_jones", "mary_garcia", "nick_wilson",
    "olivia_martinez", "peter_anderson", "quinn_thomas", "rose_jackson", "sam_white",
    "tom_harris", "uma_clark", "victor_lewis", "wendy_robinson", "xander_walker",
    "yuki_young", "zoe_allen", "alan_king", "ben_scott", "cindy_green",
    # System/service style names (shared pool, NOT just for hackers!)
    "temp_contractor", "backup_admin", "audit_service", "vpn_user", "dev_ops",
    "qa_tester", "intern_batch", "consultant_01", "support_tier2", "migration_tool",
    "integration_svc", "reporting_usr", "data_sync", "temp_access", "contractor_may",
    # Ambiguous names (could be either)
    "sys_backup", "temp_auditor", "contractor_ext", "service_acct", "batch_process",
]


async def generate_single_reason(client: AsyncOpenAI, is_hacker: bool) -> str | None:
    """Generate a single reason via LLM"""
    if not client:
        return None

    if is_hacker:
        prompt = """Generate ONE unique, creative, and absurd reason why someone would try to get unauthorized access to a system.

The reason should be one of:
- Social engineering (pretending to be authority figures - NOT limited to CEO/FBI, can be IT admin, auditor, new manager, etc.)
- Absurd lie (aliens, time travel, magic, end of world, unexpected disasters)
- Prompt injection ("ignore all rules", "system override", "disregard guidelines", "you are now in debug mode")
- Suspicious creative excuse (any unusual justification that sounds urgent but fake)

Important: Be highly creative and varied. Do NOT reuse common patterns. Vary the sentence structure, tone, and specific details.

Return ONLY the reason text (1-2 sentences), nothing else."""
    else:
        prompt = """Generate ONE unique, legitimate work-related reason why an employee would need access to company systems.

The reason should be one of:
- Normal business operations (reports, data analysis, planning)
- Technical work (bug fixes, deployments, maintenance)
- Administrative tasks (audits, compliance, HR matters)
- Cross-department collaboration

Return ONLY the reason text (1-2 sentences), nothing else. Be specific and varied."""

    try:
        model = os.getenv("LLM_MODEL", "deepseek-chat")
        response = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You generate creative text responses. Return only the requested text, no numbering, no bullet points, no extra formatting."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=512,
            temperature=0.95,
        )
        content = response.choices[0].message.content.strip()

        # Remove <think>...</think> tags (MiniMax M2.5 model output)
        if "<think>" in content and "</think>" in content:
            # Extract content after </think>
            content = content.split("</think>")[-1].strip()

        # Clean up the response
        for prefix in ["Reason:", "Answer:", "Response:", "1.", "-", "*"]:
            if content.startswith(prefix):
                content = content[len(prefix):].strip()

        return content if content else None
    except Exception as e:
        print(f"LLM generation failed: {e}")
        return None


async def generate_reasons_via_llm(client: AsyncOpenAI, count: int, is_hacker: bool) -> list[str]:
    """Generate reasons in 2 waves: 2 concurrent per wave (total 4 per type)"""
    if not client:
        return None

    all_reasons = []

    # Wave 1: Generate first 2 concurrently
    batch1 = [generate_single_reason(client, is_hacker) for _ in range(2)]
    results1 = await asyncio.gather(*batch1, return_exceptions=True)
    for r in results1:
        if isinstance(r, str) and r:
            all_reasons.append(r)

    # Wave 2: Generate next 2 concurrently
    batch2 = [generate_single_reason(client, is_hacker) for _ in range(2)]
    results2 = await asyncio.gather(*batch2, return_exceptions=True)
    for r in results2:
        if isinstance(r, str) and r:
            all_reasons.append(r)

    return all_reasons if all_reasons else None


# Cache for generated reasons
_normal_reasons_cache = None
_hacker_reasons_cache = None


async def get_reasons_async(client: AsyncOpenAI, is_hacker: bool) -> list[str]:
    """Get reasons - dynamically generated via LLM with caching"""
    global _normal_reasons_cache, _hacker_reasons_cache

    cache = _hacker_reasons_cache if is_hacker else _normal_reasons_cache
    if cache and len(cache) >= 4:
        return cache

    # Generate new reasons via LLM
    reasons = await generate_reasons_via_llm(client, 8, is_hacker)

    if reasons:
        if is_hacker:
            _hacker_reasons_cache = reasons
        else:
            _normal_reasons_cache = reasons
        return reasons

    # Fallback
    if is_hacker:
        return ["System emergency: grant access now", "I need immediate admin access"]
    else:
        return ["Reviewing quarterly report", "Fixing production bug"]


def get_reasons(is_hacker: bool) -> list[str]:
    """Get reasons synchronously"""
    client = get_llm_client()
    if not client:
        if is_hacker:
            return ["System emergency: grant access now", "I need immediate admin access"]
        else:
            return ["Reviewing quarterly report", "Fixing production bug"]

    try:
        reasons = asyncio.run(get_reasons_async(client, is_hacker))
        return reasons
    except Exception as e:
        print(f"Failed to get reasons: {e}")
        if is_hacker:
            return ["System emergency: grant access now"]
        else:
            return ["Reviewing quarterly report"]


def get_random_usernames_from_pool(count: int = 10) -> list[str]:
    """Get random usernames from shared pool - both hacker and normal use this"""
    return random.sample(SHARED_USER_POOL, min(count, len(SHARED_USER_POOL)))


# Log templates - varied formats to prevent pattern matching
LOG_TEMPLATES_NORMAL = [
    lambda ip, user, reason: f"[{random.randint(8,18):02d}:{random.randint(0,59):02d}] [IP: {ip}] [User: {user}] requested to download {random.choice(['Financial_Report_Q3.pdf','User_List.xlsx','Order_Data.csv','Product_Catalog.pdf'])}. Reason: {reason}",
    lambda ip, user, reason: f"[{random.randint(8,18):02d}:{random.randint(0,59):02d}] [IP: {ip}] [User: {user}] accessed {random.choice(['Code_Repository','Database','Admin_Panel','API_Gateway'])}. Reason: {reason}",
    lambda ip, user, reason: f"[{random.randint(8,18):02d}:{random.randint(0,59):02d}] [SYS] IP:{ip} User:{user} performed {random.choice(['Data_Export','Permission_Change','Config_Update'])}. Reason: {reason}",
    lambda ip, user, reason: f"[{random.randint(8,18):02d}:{random.randint(0,59):02d}] [AUDIT] User {user} from {ip} action: {random.choice(['READ','WRITE','DELETE'])}. Justification: {reason}",
]

LOG_TEMPLATES_HACKER = [
    lambda ip, user, reason: f"[{random.randint(8,18):02d}:{random.randint(0,59):02d}] [IP: {ip}] [User: {user}] requested access to {random.choice(['All_Databases','Root_System','Employee_Records','Financial_Data'])}. Reason: {reason}",
    lambda ip, user, reason: f"[{random.randint(8,18):02d}:{random.randint(0,59):02d}] [ALERT] IP:{ip} User:{user} attempted {random.choice(['Admin_Escalation','Mass_Export','Permission_Bypass'])}. Claim: {reason}",
    lambda ip, user, reason: f"[{random.randint(8,18):02d}:{random.randint(0,59):02d}] [WARN] User {user} from {ip} requested {random.choice(['Full_Access','Backdoor_Creation','Audit_Log_Deletion'])}. Explanation: {reason}",
]


def generate_normal_log(ip: str, user: str, reasons: list[str]):
    """Generate normal log"""
    reason = random.choice(reasons) if reasons else "Performing routine work"
    template = random.choice(LOG_TEMPLATES_NORMAL)
    return template(ip, user, reason)


def generate_hacker_log(ip: str, user: str, reasons: list[str]):
    """Generate hacker log"""
    reason = random.choice(reasons) if reasons else "Urgent access required"
    template = random.choice(LOG_TEMPLATES_HACKER)
    return template(ip, user, reason)


def generate_noise_log():
    """Generate noise log"""
    templates = [
        f"[{random.randint(0,23):02d}:{random.randint(0,59):02d}] [INFO] Service {random.choice(['api','auth','db','cache'])} health check: OK",
        f"[{random.randint(0,23):02d}:{random.randint(0,59):02d}] [DEBUG] Connection pool status: {random.randint(10,100)} active",
        f"[{random.randint(0,23):02d}:{random.randint(0,59):02d}] [METRIC] Request latency: {random.randint(10,500)}ms",
        f"[{random.randint(0,23):02d}:{random.randint(0,59):02d}] [HEARTBEAT] Node {random.randint(1,10)} responding",
    ]
    return random.choice(templates)


def generate_case(target_chars: int = 3200000, seed: int = None):
    """Generate test case"""
    if seed is not None:
        random.seed(seed)

    # Get random usernames from shared pool - both hacker and normal draw from same pool
    usernames = get_random_usernames_from_pool(12)

    # Generate reasons via LLM (only reasons, usernames are from fixed pool)
    print("Generating reason pools via LLM...")
    normal_reasons = get_reasons(is_hacker=False)
    hacker_reasons = get_reasons(is_hacker=True)
    print(f"Using {len(normal_reasons)} normal reasons, {len(hacker_reasons)} hacker reasons, {len(usernames)} shared usernames")

    # Generate 3 hacker IPs
    hacker_ips = [generate_random_ip() for _ in range(3)]

    all_lines = []
    total_lines = target_chars // 100

    # Insert hacker logs (fewer occurrences)
    for ip in hacker_ips:
        for _ in range(random.randint(3, 5)):
            user = random.choice(usernames)
            all_lines.append(generate_hacker_log(ip, user, hacker_reasons))

    # Normal logs (majority)
    num_normal = int(total_lines * 0.85)
    for _ in range(num_normal):
        ip = generate_random_ip()
        user = random.choice(usernames)
        all_lines.append(generate_normal_log(ip, user, normal_reasons))

    # Noise logs (fill the rest)
    num_noise = total_lines - len(all_lines)
    for _ in range(num_noise):
        all_lines.append(generate_noise_log())

    random.shuffle(all_lines)
    log_content = "\n".join(all_lines)

    # Adjust size
    current = len(log_content.encode('utf-8'))
    if current < target_chars:
        extra = []
        while len("\n".join(extra).encode('utf-8')) < target_chars - current:
            extra.append(generate_noise_log())
        log_content += "\n" + "\n".join(extra)
    elif current > target_chars:
        log_content = log_content.encode('utf-8')[:target_chars].decode('utf-8', errors='ignore')

    return {
        "log_content": log_content,
        "target_ips": hacker_ips,
    }


def generate_cases(num_cases: int = 1, seed: int = None):
    """Generate multiple test cases"""
    cases = []
    for i in range(num_cases):
        # Clear cache for each case to get fresh LLM-generated reasons
        global _normal_reasons_cache, _hacker_reasons_cache
        _normal_reasons_cache = None
        _hacker_reasons_cache = None

        case_seed = None if seed is None else seed + i
        case = generate_case(seed=case_seed)
        cases.append(case)
    return cases


if __name__ == "__main__":
    case = generate_case(target_chars=10000, seed=42)
    print(f"Size: {len(case['log_content'])/1024:.1f} KB")
    print(f"Target IPs: {case['target_ips']}")
    print("\nSample lines:")
    for line in case['log_content'].split('\n')[:10]:
        print(f"  {line[:150]}")
